# Generated by Django 5.2.3 on 2025-07-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prep_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('dietary', models.CharField(blank=True, max_length=200)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('location', models.CharField(max_length=200)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.CharField(max_length=100)),
                ('contact_method', models.CharField(max_length=100)),
                ('special_instructions', models.TextField(blank=True)),
            ],
        ),
    ]
