# Generated by Django 5.2.3 on 2025-07-08 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare', '0002_remove_foodpost_image2_remove_foodpost_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpost',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='prep_date',
        ),
    ]
