# Generated by Django 5.2.3 on 2025-07-08 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare', '0003_remove_foodpost_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
       migrations.AddField(
    model_name='foodpost',
    name='user',
    field=models.ForeignKey(
        null=True,
        blank=True,
        on_delete=django.db.models.deletion.CASCADE,
        to=settings.AUTH_USER_MODEL,
    ),
),

    ]
