# Generated by Django 5.2.3 on 2025-07-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare', '0004_foodpost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpost',
            name='user',
        ),
    ]
