# Generated by Django 5.2.3 on 2025-07-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare', '0006_foodpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodpost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
