# Generated by Django 5.2.3 on 2025-07-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare', '0007_foodpost_latitude_foodpost_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
