# Generated by Django 5.2.3 on 2025-07-19 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare', '0008_foodpost_picked_up'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='picked_up_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foodposts_picked_up', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodposts_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
