# Generated by Django 5.2.3 on 2025-07-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare', '0011_pickuprequest_message_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuprequest',
            name='food_post',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='requester',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PickupRequest',
        ),
    ]
